# Generated by Django 4.2.10 on 2024-02-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='ticker_symbol',
            field=models.CharField(max_length=255, null=True, verbose_name='Name'),
        ),
    ]
