# Generated by Django 4.2.10 on 2024-02-27 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0002_company_ticker_symbol'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='stock_current_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='event',
            name='stock_change_variance',
            field=models.IntegerField(choices=[(0, 'Hourly'), (1, 'Six hours'), (2, 'Daily')], default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='variance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
