# Generated by Django 4.2.10 on 2024-02-27 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0003_company_stock_current_value_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('stat_aggregation_interval', models.IntegerField(choices=[(0, 'Hourly'), (1, 'Six hours'), (2, 'Daily')], default=0)),
                ('stock_high_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('stock_low_value', models.DecimalField(decimal_places=2, default=0, max_digits=20)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_stats', to='stocks.company')),
            ],
            options={
                'verbose_name': 'Event',
            },
        ),
    ]
