# Generated by Django 4.2.10 on 2024-02-27 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocks', '0004_stats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='stock_change_variance',
            field=models.IntegerField(choices=[(1, 'Minute'), (360, 'Six hours'), (1440, 'Day')], default=1),
        ),
        migrations.AlterField(
            model_name='stats',
            name='stat_aggregation_interval',
            field=models.IntegerField(choices=[(1, 'Minute'), (360, 'Six hours'), (1440, 'Day')], default=1),
        ),
    ]
